# Generated by Django 2.0.10 on 2019-03-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashkart', '0002_auto_20190328_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
